---
title: "BGGN 213 Lecture 11"
author: "Eduardo Ramirez
date: "05/09/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PDB statistics
Import our PDB statistics CSV file and calculate percent strutures by experimental method.

```{r}
p <- read.csv("data Export Summary.csv", row.names=1)
```

```{r}
percent <- (p$Total / sum(p$Total)) * 100
names(percent) <- row.names(p)
percent
```

## Using Bio3D
Load the bio3d package
```{r}
install.packages("bio3d")
```

```{r}
library(bio3d)
```

```{r}
pdb <- read.pdb("1hsg")
```

```{r}
pdb
```

```{r}
attributes(pdb)
```

```{r}
head(pdb$atom)
```

```{r}
pdb$atom[1:2, c("eleno", "elety", "x", "y", "z")]
```

```{r}
pdb$atom$elety[1:2]
```

```{r}
plot.bio3d(pdb$atom$b[pdb$calpha], sse=pdb, typ="1", ylab="B-factor")
```

```{r}
pdb$xyz
```

```{r}
dim(pdb$xyz)
```

```{r}
pdb$xyz[ 1, atom2xyz(1:2)]
```

```{r}
ca.inds <- atom.select(pdb, "calpha")
ca.inds
```

```{r}
inds.ligand <- atom.select(pdb, "ligand")
inds.protein <- atom.select(pdb, "protein")
inds.protein
```

```{r}
pdb$atom[inds$atom,]
```

```{r}
pdb$atom[inds.ligand$atom,]
```

```{r}
pdb$atom[inds.protein$atom,]
```

```{r}
head(pdb$atom[inds.ligand$atom,])
```

```{r}
head(pdb$atom[inds.protein$atom,])
```

```{r}
pdb.ligand <- trim.pdb(pdb, inds = inds.ligand)
pdb.ligand
```

```{r}
write.pdb(pdb.ligand, file="1hsg_ligand.pdb")
```

```{r}
pdb.protein <- trim.pdb(pdb, inds=inds.protein)
```

```{r}
write.pdb(pdb.protein, file = "1hsg_protein.pdb")
```

## Aligning multiple structures
```{r}
ids <- c("1TND_B","1AGR_A","1TAG_A","1GG2_A","1KJY_A","4G5Q_A")  
files <- get.pdb(ids, split = TRUE)
```

```{r}
pdbs <- pdbaln(files, fit = TRUE)
pdbs
```

```{r}
pdbs$ali[1:5, 1:8]
```

```{r}
pdbs$resno[1:5, 1:8]
```

## Search and retrieve Adenylate kinase structures
```{r}
aa <- get.seq("1ake_A")
aa
```

```{r}
b <- blast.pdb(aa)

```

```{r}
hits <- plot(b)
```

```{r}
hits
```

```{r}
# Fetch PDBs
files <- get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE)
```

```{r}
# Align structures
pdbs <- pdbaln(files)

# Vector containing PDB codes
ids <- basename.pdb(pdbs$id)
# Draw schematic alignment
plot(pdbs, labels=ids)
```

## Principal Component Analysis
```{r}
# find invariant core
core <- core.find(pdbs) 

```

```{r}
# superimpose all structures to core
pdbs$xyz = pdbfit(pdbs, core) 

```

```{r}
# Perform PCA
pc.xray <- pca(pdbs)
plot(pc.xray)
```

```{r}
 #Visualize first principal component
pc1 <- mktrj(pc.xray, pc=1, file="pc_1.pdb")
pc1
```

# View within R with bio3d
```{r}

```

