---
title: "BGGN 213 Lecture 12"
author: "Eduardo Ramirez"
date: "5/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("bio3d")
library(bio3d)
filen.name <- get.pdb("1hsg")
```

```{r}
library(bio3d)
```

```{r}
file.name <-get.pdb("1hsg")
```

```{r}
hiv <- read.pdb(file.name)
```

```{r}
ligand <- trim.pdb(hiv, "ligand")
ligand
```

```{r}
protein <- trim.pdb(hiv, "protein")
protein
```

```{r}
write.pdb(ligand, "1hsg_ligand.pdb")
write.pdb(protein, "1hsg_protein.pdb")
```

## Process Docking Results
```{r}
library(bio3d) 
```

```{r}
res <- read.pdb("all.pdbqt", multi=TRUE)
write.pdb(res, "results.pdb")
```

Compare our results to Merk Co. drug crystal structure.

```{r}
ori <- read.pdb("ligand.pdbqt")
```

```{r}
rmsd(ori, res)
```

## Q6 RMSD based on non hydrogen atoms
```{r}
inds <- atom.select(ori, "noh")

rmsd(ori$xyz[,inds$xyz], res$xyz[ inds$xyz])
```

# Revisit Search and retrieve Adenylate Kinases
```{r}
aa <- get.seq("P69441")
aa
```

```{r}
b <- blast.pdb(aa)
plot(b)
```

```{r}
hits <- plot(b)
```

```{r}
hits$pdb.id
```

```{r}
b$hit.tbl
```

```{r}
writ.fasta(aa, file="ruby.fa")
aa2 <- read.fasta("ruby.fa")
aa2
```

```{r}
files <- get.pdb(hits$pdb.id, path="pdbs", split=TRUE, gzip=TRUE)
```

```{r}
pdbs <- pdbaln(files, fit=TRUE)
```

```{r}
View(pdbs)
```

```{r}
# Perform PCA & plot the results
pc.xray <- pca(pdbs) 
plot(pc.xray)
```

```{r}
pc1 <- mktrj(pc.xray, pc=1, file="pc_1.pdb")
```

```{r}
View(pc1)
```

