---
title: "Lecture 13"
author: "Eduardo Ramirez"
date: "5/16/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##1000 Genome Project data

Read 1000 genome data for MXL dataset

```{r}
genotype <- read.csv("373531-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378.csv")
```

```{r}
table(genotype[,2]) / nrow(genotype) * 100
```

```{r}
install.packages("seqinr")
```

```{r}
install.packages("gtools")
```

```{r}
library(seqinr)
library(gtools)
phred <- asc( s2c("DDDDCDEDCDDDDBBDDDCC@") ) - 33
phred
```

```{r}
prob <- 10**(-phred/10)
prob
```

##Population Scale Analysis
Assessing genetic differences on a population scale
Association of 4 asthma-associated SNPs (rs8067378...) on ORMDL3
```{r}
geno <- read.table("rs8067378_ENSG00000172057.6.txt")
```

```{r}
summary(geno)
```

```{r}
summary (geno$exp[geno$geno == "G/G"])
summary (geno$exp[geno$geno == "A/G"])
summary (geno$exp[geno$geno == "A/A"])
```

##Boxplot
```{r}
boxplot(exp ~ geno , data=geno, notch=TRUE)
```

##ggplot2 data analysis
```{r}
install.packages("ggplot2")
```

```{r}
library(ggplot2)
ggplot(geno, aes(geno, exp)) + geom_boxplot(notch=TRUE, outlier.shape = NA)
```

##ggplot2 histogram
```{r}
ggplot(geno, aes(exp, fill = geno)) + geom_density(alpha = 0.2)
```

##ggplot2 boxplot
```{r}
ggplot(geno, aes(geno, exp, fill=geno)) + 
  geom_boxplot(notch=TRUE, outlier.shape = NA) + 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)
```

