CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Human_KIF11         ERLQMFDDPRNKRGVIIKGLEEITVHNKDEVYQILEKGAAKRTTAATLMNAYSSRSHSVF
Caenorhabditis      ERLRIXDDP-NKKGVIVSGVEEVXVRNRXDVFKLLQXGAEKRRTAATLMNMHSSRSHSLF
CBN-BMK-1           ERLRIFDDP-NKKGVIVSGVEEVPVRNRSDVYKLLQLGAEKRRTAATLMNMHSSRSHSLF
CRE-BMK-1           ERLRIFDDP-HKKGVIVSGVEEVPVRNRSDVFKLLQLGAEKRRTAATLMNMHSSRSHSLF
Kinesin-like        ERLRIFDDP-NKKGVIVSGVEEVPVRNRSDVFKLLQLGAEKRRTAATLMNMHSSRSHSLF
                    ***.: *** :*.***:.*:**: *.*. :*:::*: ** ** ******* :******:*

Human_KIF11         SVTIHMKETTIDGEELVKIGKLNLVDLAGSENIGRSGAVDKRAREAGNINQSLLTLGRVI
Caenorhabditis      MVNVVIRENTTTGEELVKQGKLXLXDLAGSENIGRSGAQGXRAXEXGSIXXSLLTLGRVI
CBN-BMK-1           MVNVVIRENTNSGEELVKQGKLNLVDLAGSENIGRSGAQGNRAKEAGSINQSLLTLGRVI
CRE-BMK-1           MVNVVVRENTNTGEELVKQGKLNLVDLAGSENIGRSGAQGNRAKEAGSINQSLLTLGRVI
Kinesin-like        MVNVVIRENTTTGEELVKQGKLNLVDLAGSENIGRSGAQGNRAKEAGSINQSLLTLGRVI
                     *.: :.*.*  ****** *** * ************* . ** * *.*  *********
